package com.lbf.pack;


import com.aliyun.oss.OSS;
import com.aliyun.oss.internal.OSSUtils;
import com.aliyun.oss.model.GetObjectRequest;
import com.aliyun.oss.model.PutObjectRequest;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import com.lbf.pack.Util.*;
import com.lbf.pack.beans.*;
import com.lbf.pack.mapper.*;
import com.lbf.pack.service.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.mail.javamail.JavaMailSender;


import javax.mail.MessagingException;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.*;

@SpringBootTest
class LoneybearForumApplicationTests {
    @Autowired
    RedisService redisService;
    @Autowired
    UserLoginService userLoginService;
    @Autowired
    UserLoginMapper userLoginMapper;
    @Autowired
    UserDataMapper userDataMapper;
    @Autowired
    UserEditMapper userEditMapper;
    @Autowired
    JavaMailSender mailSender;
    @Value("${spring.mail.username}")
    String username;
    @Autowired
    RedisUtil redisUtil;
    @Autowired
    StringRedisTemplate redisStringTemplate;
    @Autowired
    RedisTemplate redisTemplate;
    @Autowired
    SendEmailService sendEmailService;
    @Autowired
    Zonemapper zonemapper;
    @Autowired
    QueryDataService queryDataService;
    @Autowired
    FloorMapper floorMapper;
    @Autowired
    ElasticSearchService elasticSearchService;
    @Autowired
    BlackListService blackListService;
    @Test

    void testservice(){

        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String DF = df.format(new Date());
        System.out.println(DF);
        /**
         * Select password,username from Userbean绑定的表 where username = 'root';
         */
//        QueryWrapper<UsersBean>  queryWrapper = new QueryWrapper<>();
//        queryWrapper.select("password","username").eq("username","111658973");
//        List<UsersBean> uu = usersMapper.selectList(queryWrapper);
//        UsersBean u = usersMapper.selectOne(queryWrapper);
//        uu.forEach(System.out::println);
//        System.out.println(u);

        /**
         * update users set username = ......... where username = testuser;
         */
//        UpdateWrapper<UsersBean> updateWrapper = new UpdateWrapper<>();
//        updateWrapper.eq("username","testuser");
        UserLoginBean update = new UserLoginBean();

        update.setPhoneNumber("123819381923");
        update.setUsername("柴斌峰");
        update.setPassword("ppp");
        update.setLastVisitedTime(DF);
        UUID uuid = UUID.randomUUID();
        System.out.println(uuid);
//        usersMapper.update(update,updateWrapper);




//        UsersBean userbean = new UsersBean("123456","654321",1,"","");
        userLoginMapper.insert(update);
//
//        /**
////         *
////         */
//        QueryWrapper<UsersBean> delete = new QueryWrapper<>();
//        delete.eq("username","123456");
//        usersMapper.delete(delete);


    }
    @Test
    public void testMAP(){
        UpdateWrapper<UserEditDataBean> updateWrapper = new UpdateWrapper<>();
        updateWrapper.eq("username","test");
        UserEditDataBean update = new UserEditDataBean();

        update.setPhoneNumber("123819381923");
        update.setNick("柴斌峰");
        update.setUintroduction("ppp");

        userEditMapper.update(update,updateWrapper);

    }
    @Test
    public void mail() throws MessagingException, InterruptedException {
//        for(int i=0;i<100;i++){
//            sendEmailService.sendVerifycodeMail("binfeng.chai@gmail.com",new RandomUtils().GetRandomNickName());
//            Thread.sleep(4000);
//            System.out.println(i);
//        }
                    sendEmailService.sendVerifycodeMail("Binfeng.chai@Gmail.com",new RandomUtils().GetRandomEmailVerifyCode().toString());

    }

    @Test
    public void base64() throws IOException {
//        String imageStr = Base64Utils.GetImageStr("../static/images/testUpload/test.png");
//        System.out.println(imageStr);
//        BASE64Decoder decoder = new BASE64Decoder();
//        FileOutputStream write = new FileOutputStream(new File("./src/main/resources/static/images/testUpload/user/test.png"));
//        byte[] decoderBytes = decoder.decodeBuffer("/9j/4AAQSkZJRgABAQAAkACQAAD/4QB0RXhpZgAATU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAIdpAAQAAAABAAAATgAAAAAAAACQAAAAAQAAAJAAAAABAAKgAgAEAAAAAQAAAHygAwAEAAAAAQAAAHwAAAAA/+0AOFBob3Rvc2hvcCAzLjAAOEJJTQQEAAAAAAAAOEJJTQQlAAAAAAAQ1B2M2Y8AsgTpgAmY7PhCfv/iD6xJQ0NfUFJPRklMRQABAQAAD5xhcHBsAhAAAG1udHJSR0IgWFlaIAfjAAEAEwAUACwALWFjc3BBUFBMAAAAAEFQUEwAAAAAAAAAAAAAAAAAAAAAAAD21gABAAAAANMtYXBwbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEWRlc2MAAAFQAAAAYmRzY20AAAG0AAAEhGNwcnQAAAY4AAAAI3d0cHQAAAZcAAAAFHJYWVoAAAZwAAAAFGdYWVoAAAaEAAAAFGJYWVoAAAaYAAAAFHJUUkMAAAasAAAIDGFhcmcAAA64AAAAIHZjZ3QAAA7YAAAAMG5kaW4AAA8IAAAAPmNoYWQAAA9IAAAALG1tb2QAAA90AAAAKGJUUkMAAAasAAAIDGdUUkMAAAasAAAIDGFhYmcAAA64AAAAIGFhZ2cAAA64AAAAIGRlc2MAAAAAAAAACERpc3BsYXkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABtbHVjAAAAAAAAACYAAAAMaHJIUgAAABQAAAHYa29LUgAAAAwAAAHsbmJOTwAAABIAAAH4aWQAAAAAABIAAAIKaHVIVQAAABQAAAIcY3NDWgAAABYAAAIwZGFESwAAABwAAAJGbmxOTAAAABYAAAJiZmlGSQAAABAAAAJ4aXRJVAAAABQAAAKIZXNFUwAAABIAAAKccm9STwAAABIAAAKcZnJDQQAAABYAAAKuYXIAAAAAABQAAALEdWtVQQAAABwAAALYaGVJTAAAABYAAAL0emhUVwAAAAwAAAMKdmlWTgAAAA4AAAMWc2tTSwAAABYAAAMkemhDTgAAAAwAAAMKcnVSVQAAACQAAAM6ZW5HQgAAABQAAANeZnJGUgAAABYAAANybXMAAAAAABIAAAOIaGlJTgAAABIAAAOadGhUSAAAAAwAAAOsY2FFUwAAABgAAAO4ZW5BVQAAABQAAANeZXNYTAAAABIAAAKcZGVERQAAABAAAAPQZW5VUwAAABIAAAPgcHRCUgAAABgAAAPycGxQTAAAABIAAAQKZWxHUgAAACIAAAQcc3ZTRQAAABAAAAQ+dHJUUgAAABQAAAROcHRQVAAAABYAAARiamFKUAAAAAwAAAR4AEwAQwBEACAAdQAgAGIAbwBqAGnO7LfsACAATABDAEQARgBhAHIAZwBlAC0ATABDAEQATABDAEQAIABXAGEAcgBuAGEAUwB6AO0AbgBlAHMAIABMAEMARABCAGEAcgBlAHYAbgD9ACAATABDAEQATABDAEQALQBmAGEAcgB2AGUAcwBrAOYAcgBtAEsAbABlAHUAcgBlAG4ALQBMAEMARABWAOQAcgBpAC0ATABDAEQATABDAEQAIABjAG8AbABvAHIAaQBMAEMARAAgAGMAbwBsAG8AcgBBAEMATAAgAGMAbwB1AGwAZQB1AHIgDwBMAEMARAAgBkUGRAZIBkYGKQQaBD4EOwRMBD4EQAQ+BDIEOAQ5ACAATABDAEQgDwBMAEMARAAgBeYF0QXiBdUF4AXZX2mCcgAgAEwAQwBEAEwAQwBEACAATQDgAHUARgBhAHIAZQBiAG4A/QAgAEwAQwBEBCYEMgQ1BEIEPQQ+BDkAIAQWBBoALQQ0BDgEQQQ/BDsENQQ5AEMAbwBsAG8AdQByACAATABDAEQATABDAEQAIABjAG8AdQBsAGUAdQByAFcAYQByAG4AYQAgAEwAQwBECTAJAgkXCUAJKAAgAEwAQwBEAEwAQwBEACAOKg41AEwAQwBEACAAZQBuACAAYwBvAGwAbwByAEYAYQByAGIALQBMAEMARABDAG8AbABvAHIAIABMAEMARABMAEMARAAgAEMAbwBsAG8AcgBpAGQAbwBLAG8AbABvAHIAIABMAEMARAOIA7MDxwPBA8kDvAO3ACADvwO4A8wDvQO3ACAATABDAEQARgDkAHIAZwAtAEwAQwBEAFIAZQBuAGsAbABpACAATABDAEQATABDAEQAIABhACAAQwBvAHIAZQBzMKsw6TD8AEwAQwBEdGV4dAAAAABDb3B5cmlnaHQgQXBwbGUgSW5jLiwgMjAxOQAAWFlaIAAAAAAAAPMWAAEAAAABFspYWVogAAAAAAAAgvQAAD1k////vFhZWiAAAAAAAABMJAAAtIUAAArmWFlaIAAAAAAAACe+AAAOFwAAyItjdXJ2AAAAAAAABAAAAAAFAAoADwAUABkAHgAjACgALQAyADYAOwBAAEUASgBPAFQAWQBeAGMAaABtAHIAdwB8AIEAhgCLAJAAlQCaAJ8AowCoAK0AsgC3ALwAwQDGAMsA0ADVANsA4ADlAOsA8AD2APsBAQEHAQ0BEwEZAR8BJQErATIBOAE+AUUBTAFSAVkBYAFnAW4BdQF8AYMBiwGSAZoBoQGpAbEBuQHBAckB0QHZAeEB6QHyAfoCAwIMAhQCHQImAi8COAJBAksCVAJdAmcCcQJ6AoQCjgKYAqICrAK2AsECywLVAuAC6wL1AwADCwMWAyEDLQM4A0MDTwNaA2YDcgN+A4oDlgOiA64DugPHA9MD4APsA/kEBgQTBCAELQQ7BEgEVQRjBHEEfgSMBJoEqAS2BMQE0wThBPAE/gUNBRwFKwU6BUkFWAVnBXcFhgWWBaYFtQXFBdUF5QX2BgYGFgYnBjcGSAZZBmoGewaMBp0GrwbABtEG4wb1BwcHGQcrBz0HTwdhB3QHhgeZB6wHvwfSB+UH+AgLCB8IMghGCFoIbgiCCJYIqgi+CNII5wj7CRAJJQk6CU8JZAl5CY8JpAm6Cc8J5Qn7ChEKJwo9ClQKagqBCpgKrgrFCtwK8wsLCyILOQtRC2kLgAuYC7ALyAvhC/kMEgwqDEMMXAx1DI4MpwzADNkM8w0NDSYNQA1aDXQNjg2pDcMN3g34DhMOLg5JDmQOfw6bDrYO0g7uDwkPJQ9BD14Peg+WD7MPzw/sEAkQJhBDEGEQfhCbELkQ1xD1ERMRMRFPEW0RjBGqEckR6BIHEiYSRRJkEoQSoxLDEuMTAxMjE0MTYxODE6QTxRPlFAYUJxRJFGoUixStFM4U8BUSFTQVVhV4FZsVvRXgFgMWJhZJFmwWjxayFtYW+hcdF0EXZReJF64X0hf3GBsYQBhlGIoYrxjVGPoZIBlFGWsZkRm3Gd0aBBoqGlEadxqeGsUa7BsUGzsbYxuKG7Ib2hwCHCocUhx7HKMczBz1HR4dRx1wHZkdwx3sHhYeQB5qHpQevh7pHxMfPh9pH5Qfvx/qIBUgQSBsIJggxCDwIRwhSCF1IaEhziH7IiciVSKCIq8i3SMKIzgjZiOUI8Ij8CQfJE0kfCSrJNolCSU4JWgllyXHJfcmJyZXJocmtyboJxgnSSd6J6sn3CgNKD8ocSiiKNQpBik4KWspnSnQKgIqNSpoKpsqzysCKzYraSudK9EsBSw5LG4soizXLQwtQS12Last4S4WLkwugi63Lu4vJC9aL5Evxy/+MDUwbDCkMNsxEjFKMYIxujHyMioyYzKbMtQzDTNGM38zuDPxNCs0ZTSeNNg1EzVNNYc1wjX9Njc2cjauNuk3JDdgN5w31zgUOFA4jDjIOQU5Qjl/Obw5+To2OnQ6sjrvOy07azuqO+g8JzxlPKQ84z0iPWE9oT3gPiA+YD6gPuA/IT9hP6I/4kAjQGRApkDnQSlBakGsQe5CMEJyQrVC90M6Q31DwEQDREdEikTORRJFVUWaRd5GIkZnRqtG8Ec1R3tHwEgFSEtIkUjXSR1JY0mpSfBKN0p9SsRLDEtTS5pL4kwqTHJMuk0CTUpNk03cTiVObk63TwBPSU+TT91QJ1BxULtRBlFQUZtR5lIxUnxSx1MTU19TqlP2VEJUj1TbVShVdVXCVg9WXFapVvdXRFeSV+BYL1h9WMtZGllpWbhaB1pWWqZa9VtFW5Vb5Vw1XIZc1l0nXXhdyV4aXmxevV8PX2Ffs2AFYFdgqmD8YU9homH1YklinGLwY0Njl2PrZEBklGTpZT1lkmXnZj1mkmboZz1nk2fpaD9olmjsaUNpmmnxakhqn2r3a09rp2v/bFdsr20IbWBtuW4SbmtuxG8eb3hv0XArcIZw4HE6cZVx8HJLcqZzAXNdc7h0FHRwdMx1KHWFdeF2Pnabdvh3VnezeBF4bnjMeSp5iXnnekZ6pXsEe2N7wnwhfIF84X1BfaF+AX5ifsJ/I3+Ef+WAR4CogQqBa4HNgjCCkoL0g1eDuoQdhICE44VHhauGDoZyhteHO4efiASIaYjOiTOJmYn+imSKyoswi5aL/IxjjMqNMY2Yjf+OZo7OjzaPnpAGkG6Q1pE/kaiSEZJ6kuOTTZO2lCCUipT0lV+VyZY0lp+XCpd1l+CYTJi4mSSZkJn8mmia1ZtCm6+cHJyJnPedZJ3SnkCerp8dn4uf+qBpoNihR6G2oiailqMGo3aj5qRWpMelOKWpphqmi6b9p26n4KhSqMSpN6mpqhyqj6sCq3Wr6axcrNCtRK24ri2uoa8Wr4uwALB1sOqxYLHWskuywrM4s660JbSctRO1irYBtnm28Ldot+C4WbjRuUq5wro7urW7LrunvCG8m70VvY++Cr6Evv+/er/1wHDA7MFnwePCX8Lbw1jD1MRRxM7FS8XIxkbGw8dBx7/IPci8yTrJuco4yrfLNsu2zDXMtc01zbXONs62zzfPuNA50LrRPNG+0j/SwdNE08bUSdTL1U7V0dZV1tjXXNfg2GTY6Nls2fHadtr724DcBdyK3RDdlt4c3qLfKd+v4DbgveFE4cziU+Lb42Pj6+Rz5PzlhOYN5pbnH+ep6DLovOlG6dDqW+rl63Dr++yG7RHtnO4o7rTvQO/M8Fjw5fFy8f/yjPMZ86f0NPTC9VD13vZt9vv3ivgZ+Kj5OPnH+lf65/t3/Af8mP0p/br+S/7c/23//3BhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbdmNndAAAAAAAAAABAAEAAAAAAAAAAQAAAAEAAAAAAAAAAQAAAAEAAAAAAAAAAQAAbmRpbgAAAAAAAAA2AACuAAAAUgAAAEPAAACwwAAAJoAAAA1AAABQAAAAVEAAAjMzAAIzMwACMzMAAAAAAAAAAHNmMzIAAAAAAAEMcgAABfj///MdAAAHugAA/XL///ud///9pAAAA9kAAMBxbW1vZAAAAAAAAAYQAACgPgAAAADVGGSAAAAAAAAAAAAAAAAAAAAAAP/AABEIAHwAfAMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2wBDAAICAgICAgMCAgMFAwMDBQYFBQUFBggGBgYGBggKCAgICAgICgoKCgoKCgoMDAwMDAwODg4ODg8PDw8PDw8PDw//2wBDAQICAgQEBAcEBAcQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/3QAEAAj/2gAMAwEAAhEDEQA/AP32LDGc4968q8T/ABq+GvhC6aw1zXIluYzho4w0zqf9oRq2Pxrif2kfiHeeBfA4g0qTytR1eQ28TjqigZkYe+OB6Zr8tyzsWeVi7tyWclmJ9cnk571+g8JcE/2hB1a0rQ8j5DiDid4Sfsqauz9Tx+0/8HG/5jMgx/06Tn/2Sl/4ad+Dn/Qak/8AASf/AOIr8rKK+2XhlgFopS+9f5HzL43xa6R+4/VP/hp34Of9BqT/AMBJ/wD4ij/hp34Of9BqT/wEn/8AiK/Kyin/AMQzwH80vvX+Qv8AXfF/yx+4/VP/AIad+Dn/AEGpP/ASf/4ij/hp34Of9BqT/wABJ/8A4ivysoo/4hngP5pfev8AIP8AXfF/yx+4/VP/AIad+Dn/AEGpP/ASf/4ij/hp34Of9BqT/wABJ/8A4ivysoo/4hngP5pfev8AIP8AXfF/yx+4/VP/AIad+Dn/AEGpP/ASf/4ij/hp34Of9BqT/wABJ/8A4ivysoo/4hngP5pfev8AIP8AXfF/yx+4/VP/AIad+Dn/AEGpP/ASf/4itHTP2jPhFqt0tnBryxu5wDNDJCvP+06gfrX5N0q8MG9P89KifhlgmrRnJP1T/QceOMV9qK+4/dC2u7a8to7q1lWaGQbldSCpHYgip6/PT9k74i6jb+IZPh7f3DT2V1E81qrnPlyICWVc84ZQTiv0Lr8jz/JamX4l4ap01XofoWU5lHF0FVXzP//Q/Qf9tIHd4Q54/wBPOPf/AEfn+f518MV90/tp9fCH/b//AO29fC1f0P4faZZD1f5n47xY/wDbZhRRRX2x8yFKRSfTA+v+RS9Op/DFNyjHdmipt7CUUuR6/pRkev6VPtY90V7KXYSilyPX9KQk5AUZz7Ue1j3Qezl2Cikzk57evSl+lPfUhxCiiik9mSnqe3/s4E/8Ls8NAetz/wCks2fzFfrTX5K/s3/8ls8NfW5/9JZq/WqvwfxL/wCRhH/Cv1P1bgpf7K/U/9H9Cf20+vhD/t//APbevhavun9tPr4Q/wC3/wD9t6+Fq/ofw/8A+RZD1f5n47xb/vsgp8UUs8qQQIZJJGCqqjJZmOAAB1JPamCvRPhPbQ3fxN8LW8yBkbUINwPIPzg/0r6/GYl0aFSqui/I8LC0uepGHc+9PhB+zp4Z8KaTBqPiuyTUtanUPJ5w3Rw7gPkRenHc8819Br4Z8NKoRdKtQFGB+4Tp+VboGABRgDkV/LWNzfEYiq6lWbbZ+5YPLqNGChCJif8ACM+HP+gVa/8AfhP8KT/hGfDY5/sq1/78J/hW5WVrWt6ZoGmXOr6vOLaztFLyyNwqqK5Y16rajFu79TpdOmldpWIB4a8NnppVr/35j/woPhrw1jnSrQ/9sE/wr5B179ruNr57fwZ4ck1KGLP7yRypI6ZCIrnntnBrqfh/+1L4d8TanDofinT30G8ncRKxffCXPRSSqlSTxyO9e6+HsyUPa8ra9dfuPHjnOCc+VNHq/jL4N/D/AMaWMtleaTDbzMp2XECCORG7EMuM/Qgivy38f+CdR+H3im88Maid7W5BjkxtEkL52vg9M4/Piv2ejwy5Xp2r87P2xLeOPxro84UCSWyO4j/ZdsfXqa+l8PM7rrFrDSk3CXQ8bi/LKToOvFWaPj6iiiv3Poz8tR7d+zf/AMls8NfW5/8ASWav1qr8lf2b/wDktnhr63P/AKSzV+tVfg/iX/yMF/hX6n6vwV/ur9T/0v0J/bT6+EP+3/8A9t6+Fq+6f20+vhD/ALf/AP23r4Wr+h/D/wD5FkPV/mfjvFv++yCvTPg7/wAlV8K/9f8AD/OvM+M11XgjxBB4V8ZaN4kuY2mh024jndE+8wVucZ719RmcJTwtSEVduLX3njYGajWg3sj9rz1pK8i8EfG74f8AjxAmlamkF2ettcYilH0B4I+hr1tGzzkEHuK/lfFYWpQlyVouL8z91oYiFWPNB3HV8S/tca3f3M3h/wADWUxhi1KXzJcHG471jQMOuASTj2r658U+JNN8JaHeeINWmWG1soy7E8ZwOAPcngV+Qfjzx9rHjzxfc+Kr2QrKzjyFHSGNTlFX3HGe+a+14CySpicQ8Ql7sE/v6HzPFeZQpUlR6y/BHovjzxpqfgLV5PAHw/lOi2Wh4imlhCie5nwN8kkhBbG48AEflxVddTb4o+A9auPEKhvEHheOO6gvlURyXFqzbHjlKgbsHBBPOak1lfBHxYuR4im1yDw1rk8ai/iu0byJZUAXzY5FBwWA5UjOarT3ei6D4euvh78Pbg+JNZ8RSRJeXUcbJEUQ5SCANyQWPzOeMCv0GEKHsqapwarJpt2elvid9mmfFKpJT1knDZL+up99fs8+I77xN8KNHvdScy3EAa3Z2OS3knaCT64xXy1+2R/yOGh/9eTf+htX2P8ACDwbJ4D+H2k+G7lg11Am6cr081+XA+h4r45/bJ/5G/Qv+vKT9HNfC8K1ITz3mpfC27H2Od05xyrlnukj42ooor956M/KEe3fs3/8ls8NfW5/9JZq/WqvyV/Zv/5LZ4a+tz/6SzV+tVfg/iX/AMjBf4V+p+r8Ff7q/U//0/0J/bT6+EP+3/8A9t6+Fq+6f20+vhD/ALf/AP23r4Wr+h/D/wD5FkPV/mfjvFv++yFwKsWdpdahdRWNjE09xMwVI0GWZm6AAdSar9q9I+DpH/C1PCo5/wCQhD7d6+txtd0qE6seib+48HDUlUqRg+pwE0V1Z3LQ3Eb29xEcFWBV1P0Iz+lev+Bvj38RvBKLa2uo/b7IcGC9LSqo/wBluXA9s/hX6UeM/hd4F8ewFPEelxTy4wJ1GyZf+Brg/wA6+C/i/wDs+P4F1DTpfDt2biw1STyQ1yQoil/gRpOnzdAWA56mvz/AcXZfmcVQxVNRk++33n1mLyDF4K9XDyvHy6Ed78QL3422i+HPGHio6PdGXfBbm2UWMj5wimVP3gOePm4/GvnzV9E1TQtYudC1SFor61k8t4+p3cYII6g5BBHUHIrr7b4T/EG51uPRW0S5hn3rl3UrEgxkuZT8mF653fSvuj4ZeEPD3i3xvrHjq5tE1CLTha2NncuuVlltYgssyZ6/ONob0HFa4rOMPlLbwzvBq9l0fl6nPhsFVx/Kqvxd32PCfhL+y7qfiiFNd8dmTTLBxmO2T5J5Qe5yDsHfpk19neB/g74A+H7GXw5pax3R4NxKxmmOfRnJx+GK9PVcEdvYVJX5RnXFWNx8nKrNqL+ytEfomX5Hh8PG0Y3fcE5HTHNfnh+2T/yOGif9eTf+htX6I9hX52/tk/8AI4aGf+nJv/Q2r0uAP+RpT+f5HJxZ/uMz43ooor+iOjPxtHt37N//ACWzw19bn/0lmr9aq/JX9m//AJLZ4a+tz/6SzV+tVfg/iX/yMF/hX6n6vwV/ur9T/9T9Cf20+vhD/t//APbevhavun9tPr4Q/wC3/wD9t6+Fq/ofw/8A+RZD1f5n47xb/vsha6/4f6zb+H/HGga5dcQ2N7DJJ/uhhn9DXIdqTrwenWvscTh/a0pU31TXyZ4GHq8k1PsfufBNHPFHLBIHSQBgwIIIPIIx61U1fRdL1/T5tJ1m2S7tLhdskbruVga/OX4TftM6n4I0+Lw94ltW1XTIAFhkQ7Z417Lk8MB25zX0In7Xfw1I+a11AH3hXg/99Cv50x/BuY4eq4RpuSWzR+vYXiTB1YXnKz6pncf8KA8H4+yvqGqyabn/AI8Wv5jbYHRdmfujsK9j0zStP0ewg0zS4UtbW2UJHHGu1VUdAAK+Zv8Ahrr4Zf8APvqH/flf/i6P+Gu/hl/z73//AH5X/wCLrnr5BmlVJTpSdvI2pZvl8PgmkfVPHrS/L618rf8ADXfwz/597/8A78r/APF0n/DXfwz/AOfa/wD+/K//ABdYf6rZh/z4kbf2/gv+fiPqjPbsK/ND9rfXbTVPiJaadayb3021Ecu3oHcltv1wQa9G8b/te2kunyWngbTZFuZVK/aLrAWPPcIpJJ9OcV8O6hqN7q1/capqMxnurt2kldurMxyTX6FwHwliaOI+t4mPKlsj5LijiCjVpOhRd77spUUUV+udGfniPbv2b/8Aktnhr63P/pLNX61V+Sv7N/8AyWzw19bn/wBJZq/WqvwfxL/5GC/wr9T9X4K/3V+p/9X9Cf20+vhD/t//APbevhavvL9tC0ne18KXyr+5ie7jZuwaQRMo/EI35V8G1/Q3h8/+EyHq/wAz8d4tX+2yCiiivtz5pIKKKKVx8oUUUU7hyhRRRRcOUKKKKVw5QooooDlPbv2b/wDktnhr63P/AKSzV+tVfk7+zXazTfGjQZY1ytutzI/sv2eRc/mwFfrFX4N4lv8A4UEu0V+p+q8Ff7q/U//W/a74pfD+y+Jfg+58N3D+VKzCWCTGfLmQHafpgkH2Nflj4u+F/jnwPevZ69pUqqDhZo1MkLgd1ZfX0ODX7LbVwRjrQUU8ECvrOHOLsRlydOCvDezPns64dpYx87dmfhl9ju26QSj/ALZt/hS/Ybz/AJ4y/wDftv8ACv3MCqOij8qXC+g/KvsF4rT/AOfH/kz/AMjwVwKulV/cj8MvsN5/zxl/79t/hR9hvP8AnjL/AN+2/wAK/c3C+g/KjC+g/Kn/AMRXn/z4/wDJn/kP/UVf8/n9yPwy+w3n/PGX/v23+FH2G8/54y/9+2/wr9zcL6D8qML6D8qP+Irz/wCfH/kz/wAg/wBRV/z+f3I/DL7Def8APGX/AL9t/hR9hvP+eMv/AH7b/Cv3NwvoPyowvoPyo/4ivP8A58f+TP8AyD/UVf8AP5/cj8MvsN5/zxl/79t/hR9hvP8AnjL/AN+2/wAK/c3C+g/KjC+g/Kj/AIivP/nx/wCTP/IP9RV/z+f3I/DMWF4TzDL/AN+2/wAK1NL8MeI9auVstF0u6vp3IG2OFyefXjj6niv24wPQflRtU84H5VFTxWqte7RSfnJv8LAuBYX96q2vRHyv+zx8D734fRXHiXxOV/ti9Ty0jXB+zxdSpPdievp0r6ppMDpilr80zPMquLrSr1nds+zwOCp4ekqVPZH/2Q==");
//        write.write(decoderBytes);
////        write.close();
//          String a = "/9j/4AAQSkZJRgABAQAAkACQAAD/4QB0RXhpZgAATU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAIdpAAQAAAABAAAATgAAAAAAAACQAAAAAQAAAJAAAAABAAKgAgAEAAAAAQAAAHygAwAEAAAAAQAAAHwAAAAA/+0AOFBob3Rvc2hvcCAzLjAAOEJJTQQEAAAAAAAAOEJJTQQlAAAAAAAQ1B2M2Y8AsgTpgAmY7PhCfv/iD6xJQ0NfUFJPRklMRQABAQAAD5xhcHBsAhAAAG1udHJSR0IgWFlaIAfjAAEAEwAUACwALWFjc3BBUFBMAAAAAEFQUEwAAAAAAAAAAAAAAAAAAAAAAAD21gABAAAAANMtYXBwbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEWRlc2MAAAFQAAAAYmRzY20AAAG0AAAEhGNwcnQAAAY4AAAAI3d0cHQAAAZcAAAAFHJYWVoAAAZwAAAAFGdYWVoAAAaEAAAAFGJYWVoAAAaYAAAAFHJUUkMAAAasAAAIDGFhcmcAAA64AAAAIHZjZ3QAAA7YAAAAMG5kaW4AAA8IAAAAPmNoYWQAAA9IAAAALG1tb2QAAA90AAAAKGJUUkMAAAasAAAIDGdUUkMAAAasAAAIDGFhYmcAAA64AAAAIGFhZ2cAAA64AAAAIGRlc2MAAAAAAAAACERpc3BsYXkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABtbHVjAAAAAAAAACYAAAAMaHJIUgAAABQAAAHYa29LUgAAAAwAAAHsbmJOTwAAABIAAAH4aWQAAAAAABIAAAIKaHVIVQAAABQAAAIcY3NDWgAAABYAAAIwZGFESwAAABwAAAJGbmxOTAAAABYAAAJiZmlGSQAAABAAAAJ4aXRJVAAAABQAAAKIZXNFUwAAABIAAAKccm9STwAAABIAAAKcZnJDQQAAABYAAAKuYXIAAAAAABQAAALEdWtVQQAAABwAAALYaGVJTAAAABYAAAL0emhUVwAAAAwAAAMKdmlWTgAAAA4AAAMWc2tTSwAAABYAAAMkemhDTgAAAAwAAAMKcnVSVQAAACQAAAM6ZW5HQgAAABQAAANeZnJGUgAAABYAAANybXMAAAAAABIAAAOIaGlJTgAAABIAAAOadGhUSAAAAAwAAAOsY2FFUwAAABgAAAO4ZW5BVQAAABQAAANeZXNYTAAAABIAAAKcZGVERQAAABAAAAPQZW5VUwAAABIAAAPgcHRCUgAAABgAAAPycGxQTAAAABIAAAQKZWxHUgAAACIAAAQcc3ZTRQAAABAAAAQ+dHJUUgAAABQAAAROcHRQVAAAABYAAARiamFKUAAAAAwAAAR4AEwAQwBEACAAdQAgAGIAbwBqAGnO7LfsACAATABDAEQARgBhAHIAZwBlAC0ATABDAEQATABDAEQAIABXAGEAcgBuAGEAUwB6AO0AbgBlAHMAIABMAEMARABCAGEAcgBlAHYAbgD9ACAATABDAEQATABDAEQALQBmAGEAcgB2AGUAcwBrAOYAcgBtAEsAbABlAHUAcgBlAG4ALQBMAEMARABWAOQAcgBpAC0ATABDAEQATABDAEQAIABjAG8AbABvAHIAaQBMAEMARAAgAGMAbwBsAG8AcgBBAEMATAAgAGMAbwB1AGwAZQB1AHIgDwBMAEMARAAgBkUGRAZIBkYGKQQaBD4EOwRMBD4EQAQ+BDIEOAQ5ACAATABDAEQgDwBMAEMARAAgBeYF0QXiBdUF4AXZX2mCcgAgAEwAQwBEAEwAQwBEACAATQDgAHUARgBhAHIAZQBiAG4A/QAgAEwAQwBEBCYEMgQ1BEIEPQQ+BDkAIAQWBBoALQQ0BDgEQQQ/BDsENQQ5AEMAbwBsAG8AdQByACAATABDAEQATABDAEQAIABjAG8AdQBsAGUAdQByAFcAYQByAG4AYQAgAEwAQwBECTAJAgkXCUAJKAAgAEwAQwBEAEwAQwBEACAOKg41AEwAQwBEACAAZQBuACAAYwBvAGwAbwByAEYAYQByAGIALQBMAEMARABDAG8AbABvAHIAIABMAEMARABMAEMARAAgAEMAbwBsAG8AcgBpAGQAbwBLAG8AbABvAHIAIABMAEMARAOIA7MDxwPBA8kDvAO3ACADvwO4A8wDvQO3ACAATABDAEQARgDkAHIAZwAtAEwAQwBEAFIAZQBuAGsAbABpACAATABDAEQATABDAEQAIABhACAAQwBvAHIAZQBzMKsw6TD8AEwAQwBEdGV4dAAAAABDb3B5cmlnaHQgQXBwbGUgSW5jLiwgMjAxOQAAWFlaIAAAAAAAAPMWAAEAAAABFspYWVogAAAAAAAAgvQAAD1k////vFhZWiAAAAAAAABMJAAAtIUAAArmWFlaIAAAAAAAACe+AAAOFwAAyItjdXJ2AAAAAAAABAAAAAAFAAoADwAUABkAHgAjACgALQAyADYAOwBAAEUASgBPAFQAWQBeAGMAaABtAHIAdwB8AIEAhgCLAJAAlQCaAJ8AowCoAK0AsgC3ALwAwQDGAMsA0ADVANsA4ADlAOsA8AD2APsBAQEHAQ0BEwEZAR8BJQErATIBOAE+AUUBTAFSAVkBYAFnAW4BdQF8AYMBiwGSAZoBoQGpAbEBuQHBAckB0QHZAeEB6QHyAfoCAwIMAhQCHQImAi8COAJBAksCVAJdAmcCcQJ6AoQCjgKYAqICrAK2AsECywLVAuAC6wL1AwADCwMWAyEDLQM4A0MDTwNaA2YDcgN+A4oDlgOiA64DugPHA9MD4APsA/kEBgQTBCAELQQ7BEgEVQRjBHEEfgSMBJoEqAS2BMQE0wThBPAE/gUNBRwFKwU6BUkFWAVnBXcFhgWWBaYFtQXFBdUF5QX2BgYGFgYnBjcGSAZZBmoGewaMBp0GrwbABtEG4wb1BwcHGQcrBz0HTwdhB3QHhgeZB6wHvwfSB+UH+AgLCB8IMghGCFoIbgiCCJYIqgi+CNII5wj7CRAJJQk6CU8JZAl5CY8JpAm6Cc8J5Qn7ChEKJwo9ClQKagqBCpgKrgrFCtwK8wsLCyILOQtRC2kLgAuYC7ALyAvhC/kMEgwqDEMMXAx1DI4MpwzADNkM8w0NDSYNQA1aDXQNjg2pDcMN3g34DhMOLg5JDmQOfw6bDrYO0g7uDwkPJQ9BD14Peg+WD7MPzw/sEAkQJhBDEGEQfhCbELkQ1xD1ERMRMRFPEW0RjBGqEckR6BIHEiYSRRJkEoQSoxLDEuMTAxMjE0MTYxODE6QTxRPlFAYUJxRJFGoUixStFM4U8BUSFTQVVhV4FZsVvRXgFgMWJhZJFmwWjxayFtYW+hcdF0EXZReJF64X0hf3GBsYQBhlGIoYrxjVGPoZIBlFGWsZkRm3Gd0aBBoqGlEadxqeGsUa7BsUGzsbYxuKG7Ib2hwCHCocUhx7HKMczBz1HR4dRx1wHZkdwx3sHhYeQB5qHpQevh7pHxMfPh9pH5Qfvx/qIBUgQSBsIJggxCDwIRwhSCF1IaEhziH7IiciVSKCIq8i3SMKIzgjZiOUI8Ij8CQfJE0kfCSrJNolCSU4JWgllyXHJfcmJyZXJocmtyboJxgnSSd6J6sn3CgNKD8ocSiiKNQpBik4KWspnSnQKgIqNSpoKpsqzysCKzYraSudK9EsBSw5LG4soizXLQwtQS12Last4S4WLkwugi63Lu4vJC9aL5Evxy/+MDUwbDCkMNsxEjFKMYIxujHyMioyYzKbMtQzDTNGM38zuDPxNCs0ZTSeNNg1EzVNNYc1wjX9Njc2cjauNuk3JDdgN5w31zgUOFA4jDjIOQU5Qjl/Obw5+To2OnQ6sjrvOy07azuqO+g8JzxlPKQ84z0iPWE9oT3gPiA+YD6gPuA/IT9hP6I/4kAjQGRApkDnQSlBakGsQe5CMEJyQrVC90M6Q31DwEQDREdEikTORRJFVUWaRd5GIkZnRqtG8Ec1R3tHwEgFSEtIkUjXSR1JY0mpSfBKN0p9SsRLDEtTS5pL4kwqTHJMuk0CTUpNk03cTiVObk63TwBPSU+TT91QJ1BxULtRBlFQUZtR5lIxUnxSx1MTU19TqlP2VEJUj1TbVShVdVXCVg9WXFapVvdXRFeSV+BYL1h9WMtZGllpWbhaB1pWWqZa9VtFW5Vb5Vw1XIZc1l0nXXhdyV4aXmxevV8PX2Ffs2AFYFdgqmD8YU9homH1YklinGLwY0Njl2PrZEBklGTpZT1lkmXnZj1mkmboZz1nk2fpaD9olmjsaUNpmmnxakhqn2r3a09rp2v/bFdsr20IbWBtuW4SbmtuxG8eb3hv0XArcIZw4HE6cZVx8HJLcqZzAXNdc7h0FHRwdMx1KHWFdeF2Pnabdvh3VnezeBF4bnjMeSp5iXnnekZ6pXsEe2N7wnwhfIF84X1BfaF+AX5ifsJ/I3+Ef+WAR4CogQqBa4HNgjCCkoL0g1eDuoQdhICE44VHhauGDoZyhteHO4efiASIaYjOiTOJmYn+imSKyoswi5aL/IxjjMqNMY2Yjf+OZo7OjzaPnpAGkG6Q1pE/kaiSEZJ6kuOTTZO2lCCUipT0lV+VyZY0lp+XCpd1l+CYTJi4mSSZkJn8mmia1ZtCm6+cHJyJnPedZJ3SnkCerp8dn4uf+qBpoNihR6G2oiailqMGo3aj5qRWpMelOKWpphqmi6b9p26n4KhSqMSpN6mpqhyqj6sCq3Wr6axcrNCtRK24ri2uoa8Wr4uwALB1sOqxYLHWskuywrM4s660JbSctRO1irYBtnm28Ldot+C4WbjRuUq5wro7urW7LrunvCG8m70VvY++Cr6Evv+/er/1wHDA7MFnwePCX8Lbw1jD1MRRxM7FS8XIxkbGw8dBx7/IPci8yTrJuco4yrfLNsu2zDXMtc01zbXONs62zzfPuNA50LrRPNG+0j/SwdNE08bUSdTL1U7V0dZV1tjXXNfg2GTY6Nls2fHadtr724DcBdyK3RDdlt4c3qLfKd+v4DbgveFE4cziU+Lb42Pj6+Rz5PzlhOYN5pbnH+ep6DLovOlG6dDqW+rl63Dr++yG7RHtnO4o7rTvQO/M8Fjw5fFy8f/yjPMZ86f0NPTC9VD13vZt9vv3ivgZ+Kj5OPnH+lf65/t3/Af8mP0p/br+S/7c/23//3BhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbdmNndAAAAAAAAAABAAEAAAAAAAAAAQAAAAEAAAAAAAAAAQAAAAEAAAAAAAAAAQAAbmRpbgAAAAAAAAA2AACuAAAAUgAAAEPAAACwwAAAJoAAAA1AAABQAAAAVEAAAjMzAAIzMwACMzMAAAAAAAAAAHNmMzIAAAAAAAEMcgAABfj///MdAAAHugAA/XL///ud///9pAAAA9kAAMBxbW1vZAAAAAAAAAYQAACgPgAAAADVGGSAAAAAAAAAAAAAAAAAAAAAAP/AABEIAHwAfAMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2wBDAAICAgICAgMCAgMFAwMDBQYFBQUFBggGBgYGBggKCAgICAgICgoKCgoKCgoMDAwMDAwODg4ODg8PDw8PDw8PDw//2wBDAQICAgQEBAcEBAcQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/3QAEAAj/2gAMAwEAAhEDEQA/AP32LDGc4968q8T/ABq+GvhC6aw1zXIluYzho4w0zqf9oRq2Pxrif2kfiHeeBfA4g0qTytR1eQ28TjqigZkYe+OB6Zr8tyzsWeVi7tyWclmJ9cnk571+g8JcE/2hB1a0rQ8j5DiDid4Sfsqauz9Tx+0/8HG/5jMgx/06Tn/2Sl/4ad+Dn/Qak/8AASf/AOIr8rKK+2XhlgFopS+9f5HzL43xa6R+4/VP/hp34Of9BqT/AMBJ/wD4ij/hp34Of9BqT/wEn/8AiK/Kyin/AMQzwH80vvX+Qv8AXfF/yx+4/VP/AIad+Dn/AEGpP/ASf/4ij/hp34Of9BqT/wABJ/8A4ivysoo/4hngP5pfev8AIP8AXfF/yx+4/VP/AIad+Dn/AEGpP/ASf/4ij/hp34Of9BqT/wABJ/8A4ivysoo/4hngP5pfev8AIP8AXfF/yx+4/VP/AIad+Dn/AEGpP/ASf/4ij/hp34Of9BqT/wABJ/8A4ivysoo/4hngP5pfev8AIP8AXfF/yx+4/VP/AIad+Dn/AEGpP/ASf/4itHTP2jPhFqt0tnBryxu5wDNDJCvP+06gfrX5N0q8MG9P89KifhlgmrRnJP1T/QceOMV9qK+4/dC2u7a8to7q1lWaGQbldSCpHYgip6/PT9k74i6jb+IZPh7f3DT2V1E81qrnPlyICWVc84ZQTiv0Lr8jz/JamX4l4ap01XofoWU5lHF0FVXzP//Q/Qf9tIHd4Q54/wBPOPf/AEfn+f518MV90/tp9fCH/b//AO29fC1f0P4faZZD1f5n47xY/wDbZhRRRX2x8yFKRSfTA+v+RS9Op/DFNyjHdmipt7CUUuR6/pRkev6VPtY90V7KXYSilyPX9KQk5AUZz7Ue1j3Qezl2Cikzk57evSl+lPfUhxCiiik9mSnqe3/s4E/8Ls8NAetz/wCks2fzFfrTX5K/s3/8ls8NfW5/9JZq/WqvwfxL/wCRhH/Cv1P1bgpf7K/U/9H9Cf20+vhD/t//APbevhavun9tPr4Q/wC3/wD9t6+Fq/ofw/8A+RZD1f5n47xb/vsgp8UUs8qQQIZJJGCqqjJZmOAAB1JPamCvRPhPbQ3fxN8LW8yBkbUINwPIPzg/0r6/GYl0aFSqui/I8LC0uepGHc+9PhB+zp4Z8KaTBqPiuyTUtanUPJ5w3Rw7gPkRenHc8819Br4Z8NKoRdKtQFGB+4Tp+VboGABRgDkV/LWNzfEYiq6lWbbZ+5YPLqNGChCJif8ACM+HP+gVa/8AfhP8KT/hGfDY5/sq1/78J/hW5WVrWt6ZoGmXOr6vOLaztFLyyNwqqK5Y16rajFu79TpdOmldpWIB4a8NnppVr/35j/woPhrw1jnSrQ/9sE/wr5B179ruNr57fwZ4ck1KGLP7yRypI6ZCIrnntnBrqfh/+1L4d8TanDofinT30G8ncRKxffCXPRSSqlSTxyO9e6+HsyUPa8ra9dfuPHjnOCc+VNHq/jL4N/D/AMaWMtleaTDbzMp2XECCORG7EMuM/Qgivy38f+CdR+H3im88Maid7W5BjkxtEkL52vg9M4/Piv2ejwy5Xp2r87P2xLeOPxro84UCSWyO4j/ZdsfXqa+l8PM7rrFrDSk3CXQ8bi/LKToOvFWaPj6iiiv3Poz8tR7d+zf/AMls8NfW5/8ASWav1qr8lf2b/wDktnhr63P/AKSzV+tVfg/iX/yMF/hX6n6vwV/ur9T/0v0J/bT6+EP+3/8A9t6+Fq+6f20+vhD/ALf/AP23r4Wr+h/D/wD5FkPV/mfjvFv++yCvTPg7/wAlV8K/9f8AD/OvM+M11XgjxBB4V8ZaN4kuY2mh024jndE+8wVucZ719RmcJTwtSEVduLX3njYGajWg3sj9rz1pK8i8EfG74f8AjxAmlamkF2ettcYilH0B4I+hr1tGzzkEHuK/lfFYWpQlyVouL8z91oYiFWPNB3HV8S/tca3f3M3h/wADWUxhi1KXzJcHG471jQMOuASTj2r658U+JNN8JaHeeINWmWG1soy7E8ZwOAPcngV+Qfjzx9rHjzxfc+Kr2QrKzjyFHSGNTlFX3HGe+a+14CySpicQ8Ql7sE/v6HzPFeZQpUlR6y/BHovjzxpqfgLV5PAHw/lOi2Wh4imlhCie5nwN8kkhBbG48AEflxVddTb4o+A9auPEKhvEHheOO6gvlURyXFqzbHjlKgbsHBBPOak1lfBHxYuR4im1yDw1rk8ai/iu0byJZUAXzY5FBwWA5UjOarT3ei6D4euvh78Pbg+JNZ8RSRJeXUcbJEUQ5SCANyQWPzOeMCv0GEKHsqapwarJpt2elvid9mmfFKpJT1knDZL+up99fs8+I77xN8KNHvdScy3EAa3Z2OS3knaCT64xXy1+2R/yOGh/9eTf+htX2P8ACDwbJ4D+H2k+G7lg11Am6cr081+XA+h4r45/bJ/5G/Qv+vKT9HNfC8K1ITz3mpfC27H2Od05xyrlnukj42ooor956M/KEe3fs3/8ls8NfW5/9JZq/WqvyV/Zv/5LZ4a+tz/6SzV+tVfg/iX/AMjBf4V+p+r8Ff7q/U//0/0J/bT6+EP+3/8A9t6+Fq+6f20+vhD/ALf/AP23r4Wr+h/D/wD5FkPV/mfjvFv++yFwKsWdpdahdRWNjE09xMwVI0GWZm6AAdSar9q9I+DpH/C1PCo5/wCQhD7d6+txtd0qE6seib+48HDUlUqRg+pwE0V1Z3LQ3Eb29xEcFWBV1P0Iz+lev+Bvj38RvBKLa2uo/b7IcGC9LSqo/wBluXA9s/hX6UeM/hd4F8ewFPEelxTy4wJ1GyZf+Brg/wA6+C/i/wDs+P4F1DTpfDt2biw1STyQ1yQoil/gRpOnzdAWA56mvz/AcXZfmcVQxVNRk++33n1mLyDF4K9XDyvHy6Ed78QL3422i+HPGHio6PdGXfBbm2UWMj5wimVP3gOePm4/GvnzV9E1TQtYudC1SFor61k8t4+p3cYII6g5BBHUHIrr7b4T/EG51uPRW0S5hn3rl3UrEgxkuZT8mF653fSvuj4ZeEPD3i3xvrHjq5tE1CLTha2NncuuVlltYgssyZ6/ONob0HFa4rOMPlLbwzvBq9l0fl6nPhsFVx/Kqvxd32PCfhL+y7qfiiFNd8dmTTLBxmO2T5J5Qe5yDsHfpk19neB/g74A+H7GXw5pax3R4NxKxmmOfRnJx+GK9PVcEdvYVJX5RnXFWNx8nKrNqL+ytEfomX5Hh8PG0Y3fcE5HTHNfnh+2T/yOGif9eTf+htX6I9hX52/tk/8AI4aGf+nJv/Q2r0uAP+RpT+f5HJxZ/uMz43ooor+iOjPxtHt37N//ACWzw19bn/0lmr9aq/JX9m//AJLZ4a+tz/6SzV+tVfg/iX/yMF/hX6n6vwV/ur9T/9T9Cf20+vhD/t//APbevhavun9tPr4Q/wC3/wD9t6+Fq/ofw/8A+RZD1f5n47xb/vsha6/4f6zb+H/HGga5dcQ2N7DJJ/uhhn9DXIdqTrwenWvscTh/a0pU31TXyZ4GHq8k1PsfufBNHPFHLBIHSQBgwIIIPIIx61U1fRdL1/T5tJ1m2S7tLhdskbruVga/OX4TftM6n4I0+Lw94ltW1XTIAFhkQ7Z417Lk8MB25zX0In7Xfw1I+a11AH3hXg/99Cv50x/BuY4eq4RpuSWzR+vYXiTB1YXnKz6pncf8KA8H4+yvqGqyabn/AI8Wv5jbYHRdmfujsK9j0zStP0ewg0zS4UtbW2UJHHGu1VUdAAK+Zv8Ahrr4Zf8APvqH/flf/i6P+Gu/hl/z73//AH5X/wCLrnr5BmlVJTpSdvI2pZvl8PgmkfVPHrS/L618rf8ADXfwz/597/8A78r/APF0n/DXfwz/AOfa/wD+/K//ABdYf6rZh/z4kbf2/gv+fiPqjPbsK/ND9rfXbTVPiJaadayb3021Ecu3oHcltv1wQa9G8b/te2kunyWngbTZFuZVK/aLrAWPPcIpJJ9OcV8O6hqN7q1/capqMxnurt2kldurMxyTX6FwHwliaOI+t4mPKlsj5LijiCjVpOhRd77spUUUV+udGfniPbv2b/8Aktnhr63P/pLNX61V+Sv7N/8AyWzw19bn/wBJZq/WqvwfxL/5GC/wr9T9X4K/3V+p/9X9Cf20+vhD/t//APbevhavvL9tC0ne18KXyr+5ie7jZuwaQRMo/EI35V8G1/Q3h8/+EyHq/wAz8d4tX+2yCiiivtz5pIKKKKVx8oUUUU7hyhRRRRcOUKKKKVw5QooooDlPbv2b/wDktnhr63P/AKSzV+tVfk7+zXazTfGjQZY1ytutzI/sv2eRc/mwFfrFX4N4lv8A4UEu0V+p+q8Ff7q/U//W/a74pfD+y+Jfg+58N3D+VKzCWCTGfLmQHafpgkH2Nflj4u+F/jnwPevZ69pUqqDhZo1MkLgd1ZfX0ODX7LbVwRjrQUU8ECvrOHOLsRlydOCvDezPns64dpYx87dmfhl9ju26QSj/ALZt/hS/Ybz/AJ4y/wDftv8ACv3MCqOij8qXC+g/KvsF4rT/AOfH/kz/AMjwVwKulV/cj8MvsN5/zxl/79t/hR9hvP8AnjL/AN+2/wAK/c3C+g/KjC+g/Kn/AMRXn/z4/wDJn/kP/UVf8/n9yPwy+w3n/PGX/v23+FH2G8/54y/9+2/wr9zcL6D8qML6D8qP+Irz/wCfH/kz/wAg/wBRV/z+f3I/DL7Def8APGX/AL9t/hR9hvP+eMv/AH7b/Cv3NwvoPyowvoPyo/4ivP8A58f+TP8AyD/UVf8AP5/cj8MvsN5/zxl/79t/hR9hvP8AnjL/AN+2/wAK/c3C+g/KjC+g/Kj/AIivP/nx/wCTP/IP9RV/z+f3I/DMWF4TzDL/AN+2/wAK1NL8MeI9auVstF0u6vp3IG2OFyefXjj6niv24wPQflRtU84H5VFTxWqte7RSfnJv8LAuBYX96q2vRHyv+zx8D734fRXHiXxOV/ti9Ty0jXB+zxdSpPdievp0r6ppMDpilr80zPMquLrSr1nds+zwOCp4ekqVPZH/2Q==";
//          new Base64Utils().SaveBase64(a,"./src/main/resources/static/images/testUpload/user1/BBB","aaa.png");
    }
    @Test
    public void HtmlHandler(){

    }

    @Test
    public void OssTest() throws IOException {
        AliyunOssUtil OssUtil = new AliyunOssUtil();
        OSS client = OssUtil.getDefaultClient();
        File file = new File("/Users/chaibf/Graduation的副本/src/main/resources/static/favicon.ico");
        Map<String, Object> map = OssUtil.PutLocalFile(client,"loneybear","favicon.ico", "LoneybearForum", file);
        Map<String, Object> map1 = OssUtil.PutLocalFile(client,"loneybear","favicon.ico", "LoneybearForum", file);


    }

    @Test
    public void esTEst() throws IOException {
        ElasticSearchUtil elasticSearchUtil= new ElasticSearchUtil();
//        elasticSearchUtil.ClearIndex("loneybearforum_floors");
//        elasticSearchUtil.ClearIndex("loneybearforum_users");

//        List<FloorBean> list = floorMapper.selectList(new QueryWrapper<FloorBean>());
//        List<FloorBean> list2 = new ArrayList<>();
//        for(FloorBean f:list){
//            list2.add(queryDataService.GetFloorInfoById(f.getFid()));
//        }
//        List<Map<String, Object>> maps = queryDataService.ParseToMapList(list2);
//
//        elasticSearchUtil.updateIndex("loneybearforum_floors",maps);
//        List<UserFullDataBean> listt= userDataMapper.selectList(new QueryWrapper<UserFullDataBean>());
//        List<Map<String, Object>> mapp = queryDataService.ParseToMapList(listt);
//
//        elasticSearchUtil.updateIndex("loneybearforum_users",mapp);
        elasticSearchService.init();

    }

    @Test
    public void testRedis(){

        List<String> black = redisService.scan("blacklist");
        List<Map<String, Object>> listByKeys = redisService.getListByKeys(black);
        List<Map<String, Object>> all = blackListService.getAll();

        blackListService.getALlByZname("freetalk");
        redisService.getListByKeys(black);


    }

    @Test
    public void sdad(){
        String s = new PasswordEncoderUtil().encryptPasswrod("111658974");
        String s2 = new PasswordEncoderUtil().encryptPasswrod("111658974");
        String s3 = new PasswordEncoderUtil().encryptPasswrod("111658974");

    }
}